### ISSUE TITLE
CSS Settings for browser tabs

### ISSUE THREAD

**Issue by youngkin** [ToniWonKanobi/TheSaneSafariCustomStyleSheet#1]
Master Kanobi, I'm finding the Force is weak with Safari browser tabs. Specifically, the text size is a little too small for me, and the text/background contrast is too dim on inactive tabs. Would you happen to know the CSS settings for browser tabs?

**Comment by ToniWonKanobi** [comment]
Hello! I don’t think there’s a way to adjust that, besides maybe 
adjusting the resolution of your display?

![](https://d.pr/i/3YmcKv+)

**Comment by youngkin** [comment]
Thanks for the reply! Not liking Safari’s lack of themes and limited accessibility capabilities 😉
